spring.application.name=project

server.port=80

spring.config.import=application-secret.properties

spring.datasource.url = ${db.url}
spring.datasource.username= ${db.username}
spring.datasource.password= ${db.password}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
mybatis.mapper-locations=classpath:mappers/*-mapper.xml

# Qdrant 비활성화
spring.autoconfigure.exclude=org.springframework.ai.vectorstore.qdrant.autoconfigure.QdrantVectorStoreAutoConfiguration


# Gemini 설정
spring.ai.google.genai.api-key=${gemini.key}
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite